<li class=" webdeign border-box-effect" data-category="transition"><a data-fancybox href="<?php echo $basesurl;?>images/portfolio/web/ui/1.png"><img  src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" data-src="<?php echo $basesurl;?>images/portfolio/web/thumbnail/1.png" /></a></li>
<li class=" webdeign border-box-effect" data-category="transition"><a data-fancybox href="<?php echo $basesurl;?>images/portfolio/web/ui/2.png"><img  src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" data-src="<?php echo $basesurl;?>images/portfolio/web/thumbnail/2.png" /></a></li>
<li class=" webdeign border-box-effect" data-category="transition"><a data-fancybox href="<?php echo $basesurl;?>images/portfolio/web/ui/3.png"><img  src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" data-src="<?php echo $basesurl;?>images/portfolio/web/thumbnail/3.png" /></a></li>

<li class=" webdeign border-box-effect" data-category="transition"><a data-fancybox href="<?php echo $basesurl;?>images/portfolio/web/ui/4.png"><img  src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" data-src="<?php echo $basesurl;?>images/portfolio/web/thumbnail/4.png" /></a></li>
<li class=" webdeign border-box-effect" data-category="transition"><a data-fancybox href="<?php echo $basesurl;?>images/portfolio/web/ui/5.png"><img  src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" data-src="<?php echo $basesurl;?>images/portfolio/web/thumbnail/5.png" /></a></li>
<li class=" webdeign border-box-effect" data-category="transition"><a data-fancybox href="<?php echo $basesurl;?>images/portfolio/web/ui/6.png"><img  src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" data-src="<?php echo $basesurl;?>images/portfolio/web/thumbnail/6.png" /></a></li>
<li class=" webdeign border-box-effect" data-category="transition"><a data-fancybox href="<?php echo $basesurl;?>images/portfolio/web/ui/7.png"><img  src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" data-src="<?php echo $basesurl;?>images/portfolio/web/thumbnail/7.png" /></a></li>


<li class=" webdeign border-box-effect" data-category="transition"><a data-fancybox href="<?php echo $basesurl;?>images/portfolio/web/ui/8.png"><img  src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" data-src="<?php echo $basesurl;?>images/portfolio/web/thumbnail/8.png" /></a></li>
<li class=" webdeign border-box-effect" data-category="transition"><a data-fancybox href="<?php echo $basesurl;?>images/portfolio/web/ui/9.png"><img  src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" data-src="<?php echo $basesurl;?>images/portfolio/web/thumbnail/9.png" /></a></li>
<li class=" webdeign border-box-effect" data-category="transition"><a data-fancybox href="<?php echo $basesurl;?>images/portfolio/web/ui/10.png"><img  src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" data-src="<?php echo $basesurl;?>images/portfolio/web/thumbnail/10.png" /></a></li>
<li class=" webdeign border-box-effect" data-category="transition"><a data-fancybox href="<?php echo $basesurl;?>images/portfolio/web/ui/11.png"><img  src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" data-src="<?php echo $basesurl;?>images/portfolio/web/thumbnail/11.png" /></a></li>
<li class=" webdeign border-box-effect" data-category="transition"><a data-fancybox href="<?php echo $basesurl;?>images/portfolio/web/ui/12.png"><img  src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" data-src="<?php echo $basesurl;?>images/portfolio/web/thumbnail/12.png" /></a></li>
<!-- <li class=" webdeign border-box-effect" data-category="transition"><a data-fancybox href="<?php echo $basesurl;?>images/portfolio/web/ui/13.png"><img  src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" data-src="<?php echo $basesurl;?>images/portfolio/web/thumbnail/13.png" /></a></li>
<li class=" webdeign border-box-effect" data-category="transition"><a data-fancybox href="<?php echo $basesurl;?>images/portfolio/web/ui/14.png"><img  src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" data-src="<?php echo $basesurl;?>images/portfolio/web/thumbnail/14.png" /></a></li>

<li class=" webdeign border-box-effect" data-category="transition"><a data-fancybox href="<?php echo $basesurl;?>images/portfolio/web/ui/15.png"><img  src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" data-src="<?php echo $basesurl;?>images/portfolio/web/thumbnail/15.png" /></a></li>
<li class=" webdeign border-box-effect" data-category="transition"><a data-fancybox href="<?php echo $basesurl;?>images/portfolio/web/ui/16.png"><img  src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" data-src="<?php echo $basesurl;?>images/portfolio/web/thumbnail/16.png" /></a></li> -->